# El intervalo del informe de energía de la batería se expresa en segundos.
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
# debounce del teclado
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
# Aumente la potencia de transmisión de la radio BLE del teclado para resolver problemas de latencia y comunicación deficiente entre izquierda y derecha.
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
#Cambiar el nombre de visualización del teclado predeterminado
CONFIG_ZMK_KEYBOARD_NAME="Lily58"
# Se utiliza para resolver errores relacionados con los informes de batería en Windows.
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# oled
CONFIG_ZMK_DISPLAY=y
#CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=n
# Enable a widget to show words per minute
#CONFIG_ZMK_WIDGET_WPM_STATUS=n
#CONFIG_ZMK_WIDGET_LAYER_STATUS=n
#CONFIG_ZMK_WIDGET_PERIPHERAL_STATUS=n

#Configuracion de hibernacion
# Milliseconds of inactivity before entering idle state	(10 minute)
CONFIG_ZMK_IDLE_TIMEOUT=600000
# Enable deep sleep support	
CONFIG_ZMK_SLEEP=y
# Milliseconds of inactivity before entering deep sleep (15 minutes)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Configuración de ZMK Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

#Underglow
CONFIG_ZMK_RGB_UNDERGLOW=n


#Encoder (opcion que quiero agregar en un futuro)
#CONFIG_EC11=y
#CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

#Mouse emulation
CONFIG_ZMK_POINTING=y
